swagger: "2.0"
info:
  description: REST API documentation for ALADDIN's SAAS IB customer microservice
  version: 1.0.0
  title: Aladdin SAAS IB customer Service
tags:
  - name: customer
    description: Operations available to working with SAAS IB customer service
schemes:
  - "https"
produces:
  - application/json
paths:
  /actuator2/health:
    get:
      tags:
        - API Health Check
      summary: Get Health Info
      operationId: getHealthInfo
      description: |
        Get Health Info
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
      responses:
        200:
          description: "Health Info"
          schema:
            type: "string"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Expose-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
            Cache-Control:
              type: "string"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/Error"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Expose-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
            Cache-Control:
              type: "string"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/Error"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Expose-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/Error"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Expose-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Expose-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
            Cache-Control:
              type: "string"
        500:
          description: "internal server error"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Expose-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"

definitions:
  Error:
    type: "object"
    properties:
      alerts:
        type: "array"
        items:
          $ref: "#/definitions/ErrorDetail"
  ErrorDetail:
    type: "object"
    properties:
      code:
        type: string
        description: "Code error"
        example: "500"
      message:
        type: "string"
        description: "Message error"
