swagger: "2.0"
info:
  description: REST API documentation for Notification Service
  version: 1.0.0
  title: Notification Service
tags:
  - name: notification
    description: Operations available to working with Notification Service
schemes:
  - "https"
produces:
  - application/json
paths:
  /actuator/health:
    get:
      tags:
        - API Health Check
      summary: Get Health Info
      operationId: getHealthInfo
      responses:
        200:
          description: "Health Info"
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: string
      message:
        type: string
